auth:
  NotInputData: 'Данные не были введены!'
  UserNotFound: 'Пользователь не найден.'
  WrongPassword: 'Неверный пароль.'
  Authorized: 'Вы были успешно авторизированы!'
  Authed: 'Вы уже были авторизированы!'
  Web:
    Authorisation: 'Авторизация'
    auth: 'Авторизоваться'
    login: 'Логин'
    password: 'Пароль'
Web:
  Loading: 'Загрузка...'
  ServerStopped: 'Сервер остановлен!'
  MEM: 'ОЗУ'
  CPU: 'ЦПУ'
  UserName: 'Имя пользователя'
  Cabinet: 'Личный кабинет'
  Server: 'Сервер'
  Home: 'Главная'
  Welcome: '
      <a>
        Добро пожаловать, {user}!
        <br>
        Советуем вам заглянуть в Личный Кабинет
        <br>
        Вы также можете перейти к управлению сервера используя кнопку Сервер.
      <a>
      '